const mongoose = require('mongoose');

const {Schema} = mongoose;

const bidSchema = new Schema({
    // not giving Bid Id because it will be auto generated by mongodb
    // bidId: {
    //     type: String,
    //     required: true,
    //     unique: true,
    // },
    auction: {
        type: Schema.Types.ObjectId,
        ref:'Auction',  
        min: 0,
    },
    dealerId: {
        type: Schema.Types.ObjectId,
        ref:'Dealer',  
        required: true,
    },
    bidAmount: {
        type: Number,
        required: true,
    },
    bidTime: {
        type: Date,
        default: Date.now,
    },
}, {timestamps: true});

const BidModel = mongoose.model('Bid', bidSchema);
module.exports = BidModel;